/**
 * Permission constants — mirrors backend Permission enum.
 * Used with usePermissions() hook and PermissionGate component.
 */export const P = {
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',

  // Purchase
  PURCHASE_VIEW: 'PURCHASE_VIEW',
  PURCHASE_REQUEST: 'PURCHASE_REQUEST',
  PURCHASE_REQUEST_APPROVAL: 'PURCHASE_REQUEST_APPROVAL',
  RFQS: 'RFQS',
  PURCHASE_ORDER: 'PURCHASE_ORDER',
  PURCHASE_ORDER_APPROVAL: 'PURCHASE_ORDER_APPROVAL',

  // Inbound
  INBOUND_VIEW: 'INBOUND_VIEW',
  INBOUND: 'INBOUND',
  GATE_ENTRY: 'GATE_ENTRY',
  MATERIAL_UNLOADING: 'MATERIAL_UNLOADING',
  GOODS_RECEIVING: 'GOODS_RECEIVING',
  QUALITY_CHECKING: 'QUALITY_CHECKING',
  QUALITY_APPROVAL: 'QUALITY_APPROVAL',
  GRN: 'GRN',

  // QR / Barcode
  QR_CODE_GENERATOR: 'QR_CODE_GENERATOR',
  BARCODE_SCANNER: 'BARCODE_SCANNER',

  // Putaway
  PUTAWAY_VIEW: 'PUTAWAY_VIEW',
  PUTAWAY_ASSIGNMENT_MANAGEMENT: 'PUTAWAY_ASSIGNMENT_MANAGEMENT',
  PUTAWAY_EXECUTE: 'PUTAWAY_EXECUTE',
  PUTAWAY_CONFIRMATION_MANAGEMENT: 'PUTAWAY_CONFIRMATION_MANAGEMENT',

  // Inventory
  INVENTORY_VIEW: 'INVENTORY_VIEW',
  INVENTORY_STOCK_MANAGEMENT: 'INVENTORY_STOCK_MANAGEMENT',
  INVENTORY_ADJUST: 'INVENTORY_ADJUST',

  // Fulfillment
  ORDERS_VIEW: 'ORDERS_VIEW',
  ORDERS_CREATE: 'ORDERS_CREATE',

  PICKING_VIEW: 'PICKING_VIEW',
  PICKING_EXECUTE: 'PICKING_EXECUTE',

  TROLLEYS_VIEW: 'TROLLEYS_VIEW',
  TROLLEYS_CREATE: 'TROLLEYS_CREATE',
  TROLLEYS_ASSIGN: 'TROLLEYS_ASSIGN',

  PACKING_VIEW: 'PACKING_VIEW',
  PACKING_EXECUTE: 'PACKING_EXECUTE',

  SHIPPING_VIEW: 'SHIPPING_VIEW',
  SHIPPING_CONFIRM: 'SHIPPING_CONFIRM',

  // Admin / Masters
  MASTER_VIEW: 'MASTER_VIEW',
  MASTER_MANAGE: 'MASTER_MANAGE',

  USERS_VIEW: 'USERS_VIEW',
  USERS_MANAGE: 'USERS_MANAGE',

  LABELS_VIEW: 'LABELS_VIEW',
  LABELS_PRINT: 'LABELS_PRINT',

  REPORTS_VIEW: 'REPORTS_VIEW',
  REPORTS_EXPORT: 'REPORTS_EXPORT',
};