/**
 * Permission constants — mirrors backend Permission enum.
 * Used with usePermissions() hook and PermissionGate component.
 */
export const P = {
  DASHBOARD_VIEW:   'DASHBOARD_VIEW',

  PURCHASE_VIEW:    'PURCHASE_VIEW',

  INBOUND_VIEW:     'INBOUND_VIEW',
  INBOUND_RECEIVE:  'INBOUND_RECEIVE',

  INVENTORY_VIEW:   'INVENTORY_VIEW',
  INVENTORY_ADJUST: 'INVENTORY_ADJUST',

  PUTAWAY_VIEW:     'PUTAWAY_VIEW',
  PUTAWAY_EXECUTE:  'PUTAWAY_EXECUTE',

  PICKING_VIEW:     'PICKING_VIEW',
  PICKING_EXECUTE:  'PICKING_EXECUTE',

  PACKING_VIEW:     'PACKING_VIEW',
  PACKING_EXECUTE:  'PACKING_EXECUTE',

  SHIPPING_VIEW:    'SHIPPING_VIEW',
  SHIPPING_CONFIRM: 'SHIPPING_CONFIRM',

  ORDERS_VIEW:      'ORDERS_VIEW',
  ORDERS_CREATE:    'ORDERS_CREATE',

  TROLLEYS_VIEW:    'TROLLEYS_VIEW',
  TROLLEYS_CREATE:  'TROLLEYS_CREATE',
  TROLLEYS_ASSIGN:  'TROLLEYS_ASSIGN',

  LABELS_VIEW:      'LABELS_VIEW',
  LABELS_PRINT:     'LABELS_PRINT',

  REPORTS_VIEW:     'REPORTS_VIEW',
  REPORTS_EXPORT:   'REPORTS_EXPORT',

  MASTER_VIEW:      'MASTER_VIEW',
  MASTER_MANAGE:    'MASTER_MANAGE',

  USERS_VIEW:       'USERS_VIEW',
  USERS_MANAGE:     'USERS_MANAGE',
};
